# Basic Information
title: 赵烜乐 / Xuanle Zhao
position: Ph.D. Student
affiliation: Institute of Automation, Chinese Academy of Sciences
affiliation_link: http://www.ia.ac.cn/
email: 2429527z@gmail.com
url: https://xxlllz.github.io
baseurl: ""

# Search Engine Optimization (SEO)
keywords: multimodal learning, code generation, reinforcement learning, vision-language models
description: Xuanle Zhao's Academic Homepage
canonical: https://xxlllz.github.io/

# Links
google_scholar: https://scholar.google.com.hk/citations?user=vZ4q7psAAAAJ
github_link: https://github.com/xxlllz

# Images
avatar: ./images/profile.png
favicon: ./images/favicon.ico
favicon_dark: ./images/favicon.ico

# Footnote
enable_footnote: true

# Auto Dark Mode
auto_dark_mode: true

# Font
font: "Serif" # or "Sans Serif"

# Use this project as a remote theme for GitHub Pages
remote_theme: yaoyao-liu/minimal-light

# The following files will be removed from the generated website.
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor
  - _site
  - .sass-cache
  - .jekyll-cache
  - .jekyll-metadata
  - node_modules
